version: '3'

services:
  # database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '81:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
  # wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '80:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
  # prometheus
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    restart: always
    volumes: ['./prometheus.yml:/etc/prometheus/prometheus.yml']
    networks:
      - wpsite
  # grafana
  grafana:
    image: grafana/grafana
    ports:
      - 443:3000
    restart: always
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - wpsite
  # cadvisor
  cadvisor:
    image: google/cadvisor
    ports:
      - 8080:8080
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro
    networks:
      - wpsite
  # node_exporter
  node_exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    restart: always
    networks:
      - wpsite
  # mysql_export
  mysql_exporter:
    depends_on:
      - db
    image: prom/mysqld-exporter
    ports:
      - 9104:9104
    restart: always
    environment:
      DATA_SOURCE_NAME: wordpress:wordpress@(db:3306)/
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
  grafana_storage: