groups:
- name: targets
  rules:
  - alert: instance_down
    # Condition for alerting
    expr: up == 0
    for: 5s
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 seconds.'
    # Labels - additional labels to be attached to the alert
    labels:
      severity: 'critical'

- name: host
  rules:
  - alert: high_storage_load
    expr: (node_filesystem_size_bytes{fstype="ext4"} - node_filesystem_free_bytes{fstype="ext4"}) / node_filesystem_size_bytes{fstype="ext4"} * 100 > 85
    for: 5s
    annotations:
      title: 'Server storage is almost full'
      description: 'Docker host storage usage is {{ humanize $value}}%. Reported by instance {{ $labels.job }}.'
    labels:
      severity: 'warning'
